In [ ]:
#Nhập vào từ bàn phím một xâu kí tự, hãy đếm số từ của xâu và số lần xuất hiện của từng từ trong xâu
n = input('Nhập vào một xâu kí tự: ').split()

so_tu = len(n)
print('Số từ trong xâu kí tự: ', so_tu)

so_lan_xuat_hien = {}
for i in n:
    if i in so_lan_xuat_hien:
        so_lan_xuat_hien[i] += 1
    else:
        so_lan_xuat_hien[i] = 1

for i, x in so_lan_xuat_hien.items():
    print(f'Từ {i} xuất hiện {x} lần')

In [1]:
#Cho ma trận số thực n hàng m cột, 
# a. hãy tìm phần từ lớn nhất, nhỏ nhất của ma trân.
# b. Hãy tìm điểm yên ngựa Tức là là phần tử lớn nhất trong cột 
#và nhỏ nhất trong hàng chứa nó hoặc
#là phần tử nhỏ nhất trong cột và lớn nhất trong hàng chứa nó

import numpy as np # type: ignore

# Tạo ma trận ngẫu nhiên n hàng m cột
n, m = 4, 5
ma_tran = np.random.randint(-10, 20, size=(n, m))  # Ma trận số nguyên từ -10 đến 20
print("Ma trận:\n", ma_tran)

# a. Tìm phần tử lớn nhất và nhỏ nhất của ma trận
max_value = np.max(ma_tran)
min_value = np.min(ma_tran)
print(f"Phần tử lớn nhất của ma trận: {max_value}")
print(f"Phần tử nhỏ nhất của ma trận: {min_value}")

# b. Tìm điểm yên ngựa
diem_yen_ngua = []
for i in range(n):  # Duyệt từng hàng
    for j in range(m):  # Duyệt từng cột
        # Phần tử tại vị trí (i, j)
        x = ma_tran[i][j]
        # Kiểm tra điều kiện: nhỏ nhất trong hàng và lớn nhất trong cột
        if x == np.min(ma_tran[i, :]) and x == np.max(ma_tran[:, j]):
            diem_yen_ngua.append((i, j, x))  # Lưu vị trí và giá trị điểm yên ngựa
        # Hoặc: lớn nhất trong hàng và nhỏ nhất trong cột
        elif x == np.max(ma_tran[i, :]) and x == np.min(ma_tran[:, j]):
            diem_yen_ngua.append((i, j, x))

# In kết quả điểm yên ngựa
if diem_yen_ngua:
    print("Các điểm yên ngựa (hàng, cột, giá trị):")
    for diem in diem_yen_ngua:
        print(f"Hàng {diem[0]}, Cột {diem[1]}, Giá trị: {diem[2]}")
else:
    print("Không có điểm yên ngựa nào trong ma trận.")

Ma trận:
 [[ 5 18 12 -9  8]
 [-7 10 -7 16 11]
 [-9  8  1  9 -4]
 [12 -3  2  4 13]]
Phần tử lớn nhất của ma trận: 18
Phần tử nhỏ nhất của ma trận: -9
Không có điểm yên ngựa nào trong ma trận.
